version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000" # Expose backend port for debugging
    environment:
      - SECRET_KEY=travel_tracker_secure_key_5678
      - JWT_SECRET_KEY=travel_tracker_jwt_secret_1234
      - DATABASE_URL=sqlite:////app/instance/travel_tracker.db
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./backend:/app
      - ./db:/app/instance  # SQLite database will be visible in ./db folder
    command: >
      bash -c "
        echo 'Setting up backend...' &&
        mkdir -p /app/instance &&
        chmod 777 /app/instance &&
        python /app/init_db.py &&
        gunicorn --bind 0.0.0.0:8000 'app:create_app()'
      "

  # Frontend service
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    # Simple volume to override the default nginx.conf
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf